services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - RUN_MIGRATIONS=true
    volumes:
      - db-storage:/app
    restart: unless-stopped
    networks:
      - app-network
    user: "1000:1000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-/api}
    ports:
      - "8081:80"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "5757:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db-storage:


networks:
  app-network:
    driver: bridge
