version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: production
    container_name: ai-contact-backend
    working_dir: /app
    command: bun run start
    volumes:
      - ./backend:/app
      - sqlite_data:/app
    env_file:
      - ./backend/.env
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - DB_URL=file:/app/local.db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: production
    container_name: ai-contact-frontend
    working_dir: /app
    command: [ "nginx", "-g", "daemon off;" ]
    volumes:
      - ./frontend:/app
    env_file:
      - ./frontend/.env
    ports:
      - "4173:80"
    environment:
      - NODE_ENV=production

volumes:
  sqlite_data:
    driver: local
