services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS=true
    ports:
      - "8080:8080"
    volumes:
      - db-storage:/app
    restart: unless-stopped
    networks:
      - app-network
    user: "1000:1000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-http://localhost:8080}
    ports:
      - "4173:80"
    depends_on:
      backend:
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db-storage:


networks:
  app-network:
    driver: bridge
