services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    environment:
      - RUN_MIGRATIONS=true
    volumes:
      - db-storage:/app
    restart: unless-stopped
    networks:
      - app-network
    user: "1000:1000"
    # healthcheck:
    #   test: [ "CMD-SHELL", "curl -f http://localhost:8080/v1 || exit 1" ]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    #   start_period: 40s

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL:-/api}
    ports:
      - "80:80"
    depends_on:
      backend:
        # condition: service_healthy
        condition: service_started
    restart: unless-stopped
    networks:
      - app-network

  nginx-proxy:
    image: nginx:alpine
    ports:
      - "5757:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped
    networks:
      - app-network

volumes:
  db-storage:


networks:
  app-network:
    driver: bridge
